### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by bolshakov** [bolshakov/stoplight-admin#34]
Update third-party libraries
Update stoplight and get rid of deprecation warnings

**Comment by gdeoliveira** [comment]
Will there be a version that depends on HAML 5.1.x? We would like to be able to use an option that was added to that version of HAML but we would like to avoid going all the way to HAML 6 for the time being if possible.

Also, is there an ETA for version 1.0.0 to come out?

Thank you!

**Comment by Lokideos** [comment]
Hey, @gdeoliveira!

> Will there be a version that depends on HAML 5.1.x? 

Yes, we can have a version that supports `HAML` 5.1.x.
We were also thinking about replacing `HAML` with `slim`. Do you prefer `HAML`?

> Also, is there an ETA for version 1.0.0 to come out?

I'd like to avoid commitment at this point, but I'd say that the end of March is a safe bet.

**Comment by bolshakov** [comment]
@Lokideos Let's aim to have an intermediate release that works with Stoplight 3.0 and haml 5.x. The 6th version of HAML is quite new, they introduced breaking changes and I'd prefer people to be able to use stoplight-admin without upgrading haml.

**Comment by gdeoliveira** [comment]
Thank you for the prompt response!

We would be fine with HAML 5.2.x, slim or erb. The problem we were having is that the current HAML dependency `~> 5.0.4` was preventing us from going to version 5.1.x which is where the `escape_filter_interpolations` option was added to retain the default behavior of HAML 4, something we would be interested in keeping for the time being.

Thanks again!

**Comment by bolshakov** [comment]
@gdeoliveira the 0.3.6 version has been released https://rubygems.org/gems/stoplight-admin/versions/0.3.6
